apiVersion: azure.jet.crossplane.io/v1alpha2
kind: ResourceGroup
metadata:
  name: crossplane-demo-rgr
spec:
  deletionPolicy: Delete
  forProvider:
    location: switzerlandnorth
  providerConfigRef:
    name: default
